baseURL = 'https://mehdishahdoost.com/'
languageCode = 'en-us'
title = "Mehdi's Notes"
theme= 'paper'
[params]
twitter = 'mehdi_notes'                # twitter.com/YOUR_TWITTER_ID
github = 'mehdishahdoost'                  # github.com/YOUR_GITHUB_ID
[menu]
[[menu.main]]
identifier = "about"
name = "About Me"
url = "/about/"
weight = 10