baseURL = 'https://mehdishahdoost.github.io/'
languageCode = 'en-us'
title = 'Void'
theme= 'paper'
[params]
twitter = 'm_shahdoost'                # twitter.com/YOUR_TWITTER_ID
github = 'mehdishahdoost'                  # github.com/YOUR_GITHUB_ID
